/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../app/store/store.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '../../../app/model/product.repository';
import * as import9 from '../../../app/model/cart.model';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '@angular/core/src/change_detection/change_detection_util';
import * as import13 from '../../../app/store/cartSummary.component';
import * as import14 from './cartSummary.component.ngfactory';
import * as import15 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import16 from '../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/select_control_value_accessor.ngfactory';
import * as import18 from '../../node_modules/@angular/forms/src/directives/select_multiple_control_value_accessor.ngfactory';
import * as import19 from './counter.directive.ngfactory';
import * as import20 from '@angular/common/src/pipes/number_pipe';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import23 from '@angular/router/src/router_state';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/core/src/i18n/tokens';
import * as import26 from '@angular/common/src/directives/ng_for';
import * as import27 from '@angular/router/src/directives/router_link';
import * as import28 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import29 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import30 from '../../../app/store/counter.directive';
export class Wrapper_StoreComponent {
  /*private*/ _eventHandler:Function;
  context:import0.StoreComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this._changed = false;
    this.context = new import0.StoreComponent(p0,p1,p2);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_StoreComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_StoreComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.StoreComponent>;
  _StoreComponent_0_3:Wrapper_StoreComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StoreComponent_Host0,renderType_StoreComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'store',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_StoreComponent0(this.viewUtils,this,0,this._el_0);
    this._StoreComponent_0_3 = new Wrapper_StoreComponent(this.injectorGet(import8.ProductRepository,this.parentIndex),this.injectorGet(import9.Cart,this.parentIndex),this.injectorGet(import10.Router,this.parentIndex));
    this.compView_0.create(this._StoreComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._StoreComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.StoreComponent) && (0 === requestNodeIndex))) { return this._StoreComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._StoreComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const StoreComponentNgFactory:import7.ComponentFactory<import0.StoreComponent> = new import7.ComponentFactory<import0.StoreComponent>('store',View_StoreComponent_Host0,import0.StoreComponent);
const styles_StoreComponent:any[] = ([] as any[]);
class View_StoreComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StoreComponent1,renderType_StoreComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import12.UNINITIALIZED;
    this._expr_3 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','btn btn-outline-primary btn-block'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = (this.context.$implicit == this.parentView.context.selectedCategory);
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'active',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import3.inlineInterpolate(1,'\n                ',this.context.$implicit,'\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.changeCategory(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_StoreComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  _pipe_currency_0_0:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StoreComponent2,renderType_StoreComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_14 = import12.UNINITIALIZED;
    this._expr_15 = import12.UNINITIALIZED;
    this._expr_17 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'div',new import3.InlineArray2(2,'class','panel panel-primary'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._el_4 = import3.createRenderElement(this.renderer,this._el_2,'span',new import3.InlineArray2(2,'class','pull-right pull-xs-right tag tag-pill tag-primary'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,this._el_0,'div',new import3.InlineArray2(2,'class','panel-body card-text p-a-1'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'button',new import3.InlineArray2(2,'class','btn btn-success btn-sm pull-xs-right pull-right'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n                        Add To Cart\n                    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n                ',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._pipe_currency_0_0 = import3.pureProxy4((<View_StoreComponent0>this.parentView)._pipe_currency_0.transform.bind((<View_StoreComponent0>this.parentView)._pipe_currency_0));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_10,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_10));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import12.ValueUnwrapper();
    const currVal_14:any = import3.inlineInterpolate(1,'\n                    ',this.context.$implicit.name,'\n                    ');
    if (import3.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_3,currVal_14);
      this._expr_14 = currVal_14;
    }
    valUnwrapper.reset();
    const currVal_15:any = import3.inlineInterpolate(1,'\n                    ',valUnwrapper.unwrap(import3.castByValue(this._pipe_currency_0_0,(<View_StoreComponent0>this.parentView)._pipe_currency_0.transform)(this.context.$implicit.price,'USD',true,'2.2-2')),'\n                    ');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_15,currVal_15))) {
      this.renderer.setText(this._text_5,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = import3.inlineInterpolate(1,'\n                    ',this.context.$implicit.description,'\n                    ');
    if (import3.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_9,currVal_17);
      this._expr_17 = currVal_17;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_10(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.addProductToCart(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
class View_StoreComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_StoreComponent3,renderType_StoreComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
    this._expr_2 = import12.UNINITIALIZED;
    this._expr_3 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'button',new import3.InlineArray2(2,'class','btn btn-outline-primary'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_0,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_0));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = (this.context.$implicit == this.parentView.context.selectedPage);
    if (import3.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'active',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import3.inlineInterpolate(1,'\n                ',this.context.$implicit,'\n                ');
    if (import3.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_1,currVal_3);
      this._expr_3 = currVal_3;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_0(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parentView.context.changePage(this.context.$implicit)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
var renderType_StoreComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,styles_StoreComponent,{});
export class View_StoreComponent0 extends import1.AppView<import0.StoreComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  compView_5:import1.AppView<import13.CartSummaryComponent>;
  _CartSummaryComponent_5_3:import14.Wrapper_CartSummaryComponent;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _vc_17:import11.ViewContainer;
  _TemplateRef_17_5:any;
  _NgFor_17_6:import15.Wrapper_NgFor;
  _text_18:any;
  _el_19:any;
  _RouterLink_19_3:import16.Wrapper_RouterLink;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _vc_29:import11.ViewContainer;
  _TemplateRef_29_5:any;
  _NgFor_29_6:import15.Wrapper_NgFor;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _NgSelectOption_35_3:import17.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_35_4:import18.Wrapper_NgSelectMultipleOption;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _NgSelectOption_38_3:import17.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_38_4:import18.Wrapper_NgSelectMultipleOption;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _NgSelectOption_41_3:import17.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_41_4:import18.Wrapper_NgSelectMultipleOption;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _NgSelectOption_44_3:import17.Wrapper_NgSelectOption;
  _NgSelectMultipleOption_44_4:import18.Wrapper_NgSelectMultipleOption;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _anchor_51:any;
  /*private*/ _vc_51:import11.ViewContainer;
  _TemplateRef_51_5:any;
  _CounterDirective_51_6:import19.Wrapper_CounterDirective;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  /*private*/ _expr_76:any;
  _pipe_currency_0:import20.CurrencyPipe;
  /*private*/ _expr_78:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_StoreComponent0,renderType_StoreComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._expr_76 = import12.UNINITIALIZED;
    this._expr_78 = import12.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._el_0 = import3.createRenderElement(this.renderer,parentRenderNode,'nav',new import3.InlineArray2(2,'class','navbar navbar-fixed-top navbar-inverse'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import3.createRenderElement(this.renderer,this._el_0,'a',new import3.InlineArray2(2,'class','navbar-brand'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'SPORTS STORE',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import3.createRenderElement(this.renderer,this._el_0,'cart-summary',import3.EMPTY_INLINE_ARRAY,(null as any));
    this.compView_5 = new import14.View_CartSummaryComponent0(this.viewUtils,this,5,this._el_5);
    this._CartSummaryComponent_5_3 = new import14.Wrapper_CartSummaryComponent(this.parentView.injectorGet(import9.Cart,this.parentIndex));
    this.compView_5.create(this._CartSummaryComponent_5_3.context);
    this._text_6 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_8 = import3.createRenderElement(this.renderer,parentRenderNode,'div',new import3.InlineArray4(4,'class','container','style','margin-top: 60px;'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._el_10 = import3.createRenderElement(this.renderer,this._el_8,'div',new import3.InlineArray2(2,'class','row'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','col-sm-3 col-xs-4 p-a-1'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_12,'button',new import3.InlineArray2(2,'class','btn btn-block btn-outline-primary'),(null as any));
    this._text_15 = this.renderer.createText(this._el_14,'\n                Home\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._vc_17 = new import11.ViewContainer(17,12,this,this._anchor_17);
    this._TemplateRef_17_5 = new import21.TemplateRef_(this,17,this._anchor_17);
    this._NgFor_17_6 = new import15.Wrapper_NgFor(this._vc_17.vcRef,this._TemplateRef_17_5,this.parentView.injectorGet(import22.IterableDiffers,this.parentIndex),this.ref);
    this._text_18 = this.renderer.createText(this._el_12,'\n            ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_12,'button',new import3.InlineArray8(6,'class','btn btn-danger','routerLink','/admin','style','margin-top: 30px'),(null as any));
    this._RouterLink_19_3 = new import16.Wrapper_RouterLink(this.parentView.injectorGet(import10.Router,this.parentIndex),this.parentView.injectorGet(import23.ActivatedRoute,this.parentIndex));
    this._text_20 = this.renderer.createText(this._el_19,'\n                Admin\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_23 = this.renderer.createText(this._el_10,'\n\n        ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_10,'div',new import3.InlineArray2(2,'class','col-sm-9 col-xs-8 p-a-1'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','alert alert-success'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_24,(null as any));
    this._vc_29 = new import11.ViewContainer(29,24,this,this._anchor_29);
    this._TemplateRef_29_5 = new import21.TemplateRef_(this,29,this._anchor_29);
    this._NgFor_29_6 = new import15.Wrapper_NgFor(this._vc_29.vcRef,this._TemplateRef_29_5,this.parentView.injectorGet(import22.IterableDiffers,this.parentIndex),this.ref);
    this._text_30 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_31 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','form-inline pull-xs-left m-r-1 pull-left'),(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_31,'select',new import3.InlineArray2(2,'class','form-control'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_35 = import3.createRenderElement(this.renderer,this._el_33,'option',new import3.InlineArray2(2,'value','3'),(null as any));
    this._NgSelectOption_35_3 = new import17.Wrapper_NgSelectOption(new import24.ElementRef(this._el_35),this.renderer,(null as any));
    this._NgSelectMultipleOption_35_4 = new import18.Wrapper_NgSelectMultipleOption(new import24.ElementRef(this._el_35),this.renderer,(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'3 per Page',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_38 = import3.createRenderElement(this.renderer,this._el_33,'option',new import3.InlineArray2(2,'value','4'),(null as any));
    this._NgSelectOption_38_3 = new import17.Wrapper_NgSelectOption(new import24.ElementRef(this._el_38),this.renderer,(null as any));
    this._NgSelectMultipleOption_38_4 = new import18.Wrapper_NgSelectMultipleOption(new import24.ElementRef(this._el_38),this.renderer,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'4 per Page',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_41 = import3.createRenderElement(this.renderer,this._el_33,'option',new import3.InlineArray2(2,'value','6'),(null as any));
    this._NgSelectOption_41_3 = new import17.Wrapper_NgSelectOption(new import24.ElementRef(this._el_41),this.renderer,(null as any));
    this._NgSelectMultipleOption_41_4 = new import18.Wrapper_NgSelectMultipleOption(new import24.ElementRef(this._el_41),this.renderer,(null as any));
    this._text_42 = this.renderer.createText(this._el_41,'6 per Page',(null as any));
    this._text_43 = this.renderer.createText(this._el_33,'\n                    ',(null as any));
    this._el_44 = import3.createRenderElement(this.renderer,this._el_33,'option',new import3.InlineArray2(2,'value','8'),(null as any));
    this._NgSelectOption_44_3 = new import17.Wrapper_NgSelectOption(new import24.ElementRef(this._el_44),this.renderer,(null as any));
    this._NgSelectMultipleOption_44_4 = new import18.Wrapper_NgSelectMultipleOption(new import24.ElementRef(this._el_44),this.renderer,(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'8 per Page',(null as any));
    this._text_46 = this.renderer.createText(this._el_33,'\n                ',(null as any));
    this._text_47 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_24,'\n            ',(null as any));
    this._el_49 = import3.createRenderElement(this.renderer,this._el_24,'div',new import3.InlineArray2(2,'class','btn-group pull-xs-right pull-right'),(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'\n                ',(null as any));
    this._anchor_51 = this.renderer.createTemplateAnchor(this._el_49,(null as any));
    this._vc_51 = new import11.ViewContainer(51,49,this,this._anchor_51);
    this._TemplateRef_51_5 = new import21.TemplateRef_(this,51,this._anchor_51);
    this._CounterDirective_51_6 = new import19.Wrapper_CounterDirective(this._vc_51.vcRef,this._TemplateRef_51_5);
    this._text_52 = this.renderer.createText(this._el_49,'\n            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_10,'\n    ',(null as any));
    this._text_55 = this.renderer.createText(this._el_8,'\n\n    \n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    this._pipe_currency_0 = new import20.CurrencyPipe(this.parentView.injectorGet(import25.LOCALE_ID,this.parentIndex));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray2(2,'change',(null as any)),this.eventHandler(this.handleEvent_33));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._anchor_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.CartSummaryComponent) && (5 === requestNodeIndex))) { return this._CartSummaryComponent_5_3.context; }
    if (((token === import21.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import26.NgFor) && (17 === requestNodeIndex))) { return this._NgFor_17_6.context; }
    if (((token === import27.RouterLink) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLink_19_3.context; }
    if (((token === import21.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import26.NgFor) && (29 === requestNodeIndex))) { return this._NgFor_29_6.context; }
    if (((token === import28.NgSelectOption) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgSelectOption_35_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._NgSelectMultipleOption_35_4.context; }
    if (((token === import28.NgSelectOption) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgSelectOption_38_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._NgSelectMultipleOption_38_4.context; }
    if (((token === import28.NgSelectOption) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NgSelectOption_41_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._NgSelectMultipleOption_41_4.context; }
    if (((token === import28.NgSelectOption) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._NgSelectOption_44_3.context; }
    if (((token === import29.NgSelectMultipleOption) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._NgSelectMultipleOption_44_4.context; }
    if (((token === import21.TemplateRef) && (51 === requestNodeIndex))) { return this._TemplateRef_51_5; }
    if (((token === import30.CounterDirective) && (51 === requestNodeIndex))) { return this._CounterDirective_51_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CartSummaryComponent_5_3.ngDoCheck(this,this._el_5,throwOnChange);
    const currVal_17_0_0:any = this.context.categories;
    this._NgFor_17_6.check_ngForOf(currVal_17_0_0,throwOnChange,false);
    this._NgFor_17_6.ngDoCheck(this,this._anchor_17,throwOnChange);
    const currVal_19_0_0:any = '/admin';
    this._RouterLink_19_3.check_routerLink(currVal_19_0_0,throwOnChange,false);
    this._RouterLink_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_29_0_0:any = this.context.products;
    this._NgFor_29_6.check_ngForOf(currVal_29_0_0,throwOnChange,false);
    this._NgFor_29_6.ngDoCheck(this,this._anchor_29,throwOnChange);
    const currVal_35_0_0:any = '3';
    this._NgSelectOption_35_3.check_value(currVal_35_0_0,throwOnChange,false);
    this._NgSelectOption_35_3.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_35_1_0:any = '3';
    this._NgSelectMultipleOption_35_4.check_value(currVal_35_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_35_4.ngDoCheck(this,this._el_35,throwOnChange);
    const currVal_38_0_0:any = '4';
    this._NgSelectOption_38_3.check_value(currVal_38_0_0,throwOnChange,false);
    this._NgSelectOption_38_3.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_38_1_0:any = '4';
    this._NgSelectMultipleOption_38_4.check_value(currVal_38_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_38_4.ngDoCheck(this,this._el_38,throwOnChange);
    const currVal_41_0_0:any = '6';
    this._NgSelectOption_41_3.check_value(currVal_41_0_0,throwOnChange,false);
    this._NgSelectOption_41_3.ngDoCheck(this,this._el_41,throwOnChange);
    const currVal_41_1_0:any = '6';
    this._NgSelectMultipleOption_41_4.check_value(currVal_41_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_41_4.ngDoCheck(this,this._el_41,throwOnChange);
    const currVal_44_0_0:any = '8';
    this._NgSelectOption_44_3.check_value(currVal_44_0_0,throwOnChange,false);
    this._NgSelectOption_44_3.ngDoCheck(this,this._el_44,throwOnChange);
    const currVal_44_1_0:any = '8';
    this._NgSelectMultipleOption_44_4.check_value(currVal_44_1_0,throwOnChange,false);
    this._NgSelectMultipleOption_44_4.ngDoCheck(this,this._el_44,throwOnChange);
    const currVal_51_0_0:any = this.context.pageCount;
    this._CounterDirective_51_6.check_counter(currVal_51_0_0,throwOnChange,false);
    this._CounterDirective_51_6.ngDoCheck(this,this._anchor_51,throwOnChange);
    this._vc_17.detectChangesInNestedViews(throwOnChange);
    this._vc_29.detectChangesInNestedViews(throwOnChange);
    this._vc_51.detectChangesInNestedViews(throwOnChange);
    const currVal_76:any = import3.inlineInterpolate(1,'\n                ',this.context.products.length,' Products\n            ');
    if (import3.checkBinding(throwOnChange,this._expr_76,currVal_76)) {
      this.renderer.setText(this._text_27,currVal_76);
      this._expr_76 = currVal_76;
    }
    const currVal_78:any = this.context.productsPerPage;
    if (import3.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this.renderer.setElementProperty(this._el_33,'value',currVal_78);
      this._expr_78 = currVal_78;
    }
    this.compView_5.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this._vc_17.destroyNestedViews();
    this._vc_29.destroyNestedViews();
    this._vc_51.destroyNestedViews();
    this.compView_5.destroy();
    this._NgSelectOption_35_3.ngOnDestroy();
    this._NgSelectMultipleOption_35_4.ngOnDestroy();
    this._NgSelectOption_38_3.ngOnDestroy();
    this._NgSelectMultipleOption_38_4.ngOnDestroy();
    this._NgSelectOption_41_3.ngOnDestroy();
    this._NgSelectMultipleOption_41_4.ngOnDestroy();
    this._NgSelectOption_44_3.ngOnDestroy();
    this._NgSelectMultipleOption_44_4.ngOnDestroy();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 17)) { return new View_StoreComponent1(this.viewUtils,this,17,this._anchor_17,this._vc_17); }
    if ((nodeIndex == 29)) { return new View_StoreComponent2(this.viewUtils,this,29,this._anchor_29,this._vc_29); }
    if ((nodeIndex == 51)) { return new View_StoreComponent3(this.viewUtils,this,51,this._anchor_51,this._vc_51); }
    return (null as any);
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.changeCategory()) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    result = (this._RouterLink_19_3.handleEvent(eventName,$event) && result);
    return result;
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'change')) {
      const pd_sub_0:any = ((<any>this.context.changePageSize($event.target.value)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}